### ISSUE TITLE
Enable tracer count to be determined at run time

### ISSUE THREAD

**Issue by TomasTorsvik** [NorESMhub/BLOM#105]
For discussion:
If we should have a BLOM/iHAMOCC model that can accommodate different BGC tracer counts at run time, it is necessary to first make some changes in the BLOM/iHAMOCC interface, and the way that the tracer module works. I propose the following changes:

- make "ntr" adjustable at runtime through a new subroutine ("set_trc") and change the attribute from PARAMETER to PROTECTED.
- Make the tracer arrays allocatable: trc, trcold, uflxtr, vflxtr, trflx
- Make a new "allocate_tracers" subroutine
- Set value of "ntrbgc" based on variable settings in input namelist (e.g. "with_cfc", "with_natDIC", "with_AGG", "with_ciso" as .true. or .false.)
  - advantage: No need for "double booking" of i_base, i_iso, i_cfc, i_agg, i_nat_dic 

This setup will require the following procedure:
1. Read namelist for iHAMOCC tracer variables
2. Set "ntrbgc"
3. Set "ntr"
4. Allocate tracer arrays

After that the model structure should be the same as before, so I don't think there is a need for major restructuring of the code. However, the tracer allocation will have to be included somewhere in the initialization procedure.

**Comment by TomasTorsvik** [comment]
This issue should be addressed before progress can be made on #104.

**Comment by TomasTorsvik** [comment]
I discussed this with Jörg today. As a first step we suggest to get rid of the duplication of code between BLOM (mod_tracers.F90) and iHAMOCC (mo_param1_bgc), by using the  `ntrbgc` (`nocetra`) parameter from iHAMOCC in mod_tracers.F90. This can be included in a separate `#ifdef HAMOCC` code section in mo_tracers. If you agree, I can make the required changes and create a new pull request.

**Comment by matsbn** [comment]
It makes a lot of sense to define these parameters once and that HAMOCC is "responsible". With respect to allocatable arrays, it has in the past been a performance argument for using static memory. My understanding is that this might not be a valid argument anymore. It would be extremely useful if one could test the performance of allocatable arrays somehow in a realistic configuration.

**Comment by TomasTorsvik** [comment]
> It makes a lot of sense to define these parameters once and that HAMOCC is "responsible". With respect to allocatable arrays, it has in the past been a performance argument for using static memory. My understanding is that this might not be a valid argument anymore. It would be extremely useful if one could test the performance of allocatable arrays somehow in a realistic configuration.

Sounds like a good idea! :)
I can set up a test branch. I assume all we need to do is make `trc` and trc-dependent arrays allocatable (?) We can discuss it later today.

**Comment by TomasTorsvik** [comment]
Issue closed when merging #112 . I will keep this issue open until I can do some testing with allocatable `trc`, then we can discuss if this is a direction we want to go.

**Comment by TomasTorsvik** [comment]
Here are results from some tests I did on Betzy and Fram:
[alloc_array_perf.pdf](https://github.com/NorESMhub/BLOM/files/7161038/alloc_array_perf.pdf)

It seems that there still can be some issues when replacing static arrays with allocatable ones, but perhaps only for specific compiler settings or case parameters. For most tests the differences were fairly small.

**Comment by TomasTorsvik** [comment]
@matsbn @JorgSchwinger @AleksiNummelin @milicak 
Here are results from some tests I did on Betzy and Fram:
[alloc_array_perf.txt](https://github.com/NorESMhub/BLOM/files/7161071/alloc_array_perf.txt)

It seems that there still can be some issues when replacing static arrays with allocatable ones, but perhaps only for specific compiler settings or case parameters. For most tests the differences were fairly small.

**Comment by jmaerz** [comment]
Hi @TomasTorsvik , I believe this issue became obsolete with the code restructuring carried out by Mariana for release NorESM2.1, right? - so we could close the issue, if I am not mistaken.

**Comment by TomasTorsvik** [comment]
Yes, I think this issue is obsolete.
