### ISSUE TITLE
Update and tag v1.2.0?

### ISSUE THREAD

**Issue by TomasTorsvik** [NorESMhub/BLOM#139]
@matsbn @JorgSchwinger 
Would it make sense to update the release-1.2 branch with the latest commit from Jörg and the pull request I mad just now to ``master``? Note that we have not yet created a v1.2.0 tag, or a code release for v1.2, only a release branch.

**Comment by matsbn** [comment]
Great that you bring this up @TomasTorsvik. I talked to @JorgSchwinger about this on Friday and bringing in his latest commit to the release-1.2 branch and create a v1.2.0 tag would be good to do now. Also your latest PR make sense to include in the release.

**Comment by TomasTorsvik** [comment]
It seems I'm not able to push a tag from my local clone to the main repository. I can create a release, that will also create a tag, but in that case I would like to create a release for v1.1.0 first.

**Comment by matsbn** [comment]
I can try to create the v1.2.0 tag. I saw the release-blom1.1.0 under releases. Will it be a conflict if a create the release tag wrt to release-blom1.2.0? I was wondering about the name "release-blom1.1.0". Does the name need to contain "release" and "blom" when it is listed under releases in the BLOM repository? Why not just "v1.1.0" so it is consistent with the tag name?

**Comment by TomasTorsvik** [comment]
Hi, @matsbn , it would be nice if you can create a v1.2.0 tag. I am not able to push tags from my local clone to the main repository. I think it is also possible to create tags when you create a release, but apparently it is difficult on GitHub without going through the release process. I named the release following the form for noresm releases, but probably just "v1.1.0" is more conventional, so I have re-named the release. Release names are not tracked in the git system (unlike tag names), so re-naming shouldn't cause problems, except perhaps for references in external documentation.

**Comment by matsbn** [comment]
Thanks @TomasTorsvik! I have created the v1.2.0 tag now.
