### ISSUE TITLE
iHAMOCC: change N-fixation limitation from surface mixed layer to euphotic zone?

### ISSUE THREAD

**Issue by TomasTorsvik** [NorESMhub/BLOM#153]
Currently (BLOM/iHAMOCC v1.2) the N-fixation by cyano bacteria is limited to the surface mixed layer. It might make more sense to instead limit the N-fixation to the euphotic zone, currently set as a parameter at 100.0 m depth. This will change the model output, so it is a question when and where to introduce this change; (a) in connection with introduction of hybrid vertical coordinates, or (b) in connection with nitrogen cycle implementation. I think it makes most sense to see this in connection with the N-cycle implementation, but it could also be done in a separate step.

**Comment by tjiputra** [comment]
I also think it's best to go with option (b). Scientifically, it'd be more logical when comparing different simulations or when merging code versions.

**Comment by JorgSchwinger** [comment]
With the new coordinates the upper 2 layers of the model are quite thin, i.e. the volume for N-fixation is small und thus PP will be reduced somewhat. So in this regard, the change belongs to the new vertical coordinates.

**Comment by TomasTorsvik** [comment]
If PR #154 is accepted, the N-fixation should take place over the entire mixed layer depth (defined by the kOBL index). This will hopefully solve the issue with the 2 top layers being very thin, at least for the first implementation. It has the advantage that the code change should be "minimal", in the sense that the vertical coordinate change will not coincide with another conceptual code change.

**Comment by tjiputra** [comment]
I thought the idea is to limit N2 fixation to the euphotic zone, and not the whole MLD. According to this, N2-fixation requires lights: https://www.sciencedirect.com/science/article/pii/S1385110104000930, though probably during deep MLD, temperature limitation come into effect.

**Comment by TomasTorsvik** [comment]
I agree that we should have N2 fixation in the euphotic zone, but in the first instance I would like to have a version that is mostly backwards compatible with CMIP6 simulations, so that we can evaluate "pure" coordinate changes. Perhaps this will only be a short-lived intermediate step, but I think it is safer to do it one step at a time.

**Comment by jmaerz** [comment]
Maybe it's worth thinking about another 2D field similar to `kmle` in #154 to indicate the depth of the euphotic zone? - so making it possible to differentiate between MLD and euphotic zone depth - then one has the possibility to switch between the two cases during run time for the cyanobacteria by initializing the field either via i) the current MLD or ii) a constant value (or iii) potentially even a value based on light intensity).

**Comment by TomasTorsvik** [comment]
The depth of the euphotic zone is currently set to a fixed value `dp_ez = 100.0`, but the k-index `kwrbioz` corresponding to this depth is already a 2D field. It should be fairly straight forward to extend the `set_vgrid` routine to change the calculation for `kwrbioz`. I suppose it could have a significant effect in `ocprod` if we decide to change the definition of this field.

**Comment by jmaerz** [comment]
Hi Tomas, I wouldn't touch `ocprod` here (since, as you pointed out, setting `kwrbioz` differently would change a lot in `ocprod`) and was more thinking about an analogue of `kwrbioz` for the cyanobacteria only (e.g. `kwrcyaz` or similar) - which you then can use as described earlier.

**Comment by JorgSchwinger** [comment]
As a starting point, we could just use `kwrbioz` as it is, also for the nitrogen fixation? If the process needs enough light(?), then this would be more justifiable than using mld. But since this would break backwards-compatibility we should probably introduce this at a well defined point...

**Comment by jmaerz** [comment]
With #269 , it will be possible to switch between the two options (euphotic zone only or MLD).

**Comment by jmaerz** [comment]
I close this issue, since with recent v1.6.0, we have this ability as an option (recent new default is that cyanobacteria growth only happens in the euphotic zone), while v1.6.0 has an option  to revert back to the MLD formulation, see also #269, using the switch `leuphotic_cya`.
