### ISSUE TITLE
DMSPH preprocessor flag and use of pi_ph

### ISSUE THREAD

**Issue by TomasTorsvik** [NorESMhub/BLOM#159]
@tjiputra @JorgSchwinger 
We have a CPP flag ``DMSPH`` that determines if we calculate the field ``pi_ph``. This is used in ``ocprod`` to calculate [``dms_ph``](https://github.com/NorESMhub/BLOM/blob/82cc25e9921d791d2d634961291d6ee24bc29c8c/hamocc/ocprod.F90#L455-L458) which in turn is used to calculate ``dmsprod``. At the moment ``pi_ph`` is not used and we set ``dms_ph = 1.``, so everything related to the ``DMSPH`` CPP flag is bypassed.

Should we maintain the option to set ``dms_ph`` from ``pi_ph``? If so, can we replace the ``DMSPH`` CPP flag with a logical option that we can read from a namelist file (.e.g. ``with_dmsph``) and make an if statement to select how to set ``dms_ph``?

**Comment by tjiputra** [comment]
@TomasTorsvik 
We should keep the option to set dms_ph as a function of pH. This was the code base for experiments documented in Schwinger et al. (2017).

I am not sure what is the best approach (CPP flag or namelist variable) and I am fine with either way. Note that the flag is also used in hamocc_init.F and mo_carbch.F90

**Comment by TomasTorsvik** [comment]
OK, I can set this up with a namelist option instead of the current CPP flag.

**Comment by JorgSchwinger** [comment]
Yes, the option should be kept for now, but I agree this could be made into a logical flag relatively easy.
