### ISSUE TITLE
Add pause-resume function

### ISSUE THREAD

**Issue by blcc** [NorESMhub/BLOM#178]
Hi,
I implied pause-resume in BLOM. Pause-resume is function introduced in CESM2, which let components output restart files, modify them with ESP component and read them back. It is useful for data assimilation without stop whole model.
The pull request is send.

Regards,
Ping-Gin

**Comment by blcc** [comment]
I would like to ask which branch should it make pull request? Or just request for review?

**Comment by matsbn** [comment]
Looks like a nice feature, @blcc!  Have you verified that it does not break NorESM cases (e.g no change in results, also after restart) that do not use the pause-resume function?

**Comment by blcc** [comment]
Yes @matsbn, I verified it with NorESM master branch. It output identical values with daily pause-resume enabled.
Only difference is it takes about 45 seconds to pause and resume.
The combination with multiple instance is also verified.
