### ISSUE TITLE
Change last remaining fixed form .F files to free form .F90 files in iHAMOCC

### ISSUE THREAD

**Issue by TomasTorsvik** [NorESMhub/BLOM#180]
@JorgSchwinger @jmaerz @tjiputra 
I would like to change the last remaining fixed form .F files in iHAMOCC to free form .F90 to make the source code base more consistent. In recent years we have been migrating to .F90 when we have made significant changes in in the source files, and now only 5 files remain with fixed form:

> hamocc_init.F
> hamocc_step.F
> ncout_hamocc.F
> restart_hamoccwt.F
> trc_limitc.F

Technically, the format change can be done very quickly, and we can do a renaming of the files to preserve the revision history. However, once the files have been renamed, it can become messy to merge in code changes that are currently residing in development branches and that rely on the current fixed form files. Therefore I would like to open up this discussion to determine when it would be a good time (least disruptive) to make this code change.

**Comment by jmaerz** [comment]
Hi @TomasTorsvik , thanks for the initiative. One quick question: Do you intend to rewrite the code into F90 as well? - or just renaming?

**Comment by TomasTorsvik** [comment]
> Hi @TomasTorsvik , thanks for the initiative. One quick question: Do you intend to rewrite the code into F90 as well? - or just renaming?

Hi @jmaerz , I was thinking to do a very basic code update : 
- Replace comment line formatting 'c --> !'
- Replace fixed form line continuation : '.' in 5th column --> '&'
- Remove some leading fixed form whitespace

This can be done automatically by a scripting tool.

**Comment by jmaerz** [comment]
Hi Tomas, ok, this sounds feasible and shouldn't interfere too much with my developments. As long as the changes are done in two steps (renaming and modifying the files committed separately), I don't see any real problem.
