### ISSUE TITLE
Recode mapping between pore water and ocean tracers 

### ISSUE THREAD

**Issue by jmaerz** [NorESMhub/BLOM#191]
Hi @JorgSchwinger and @TomasTorsvik , in the course of the implementation for the nitrogen cycle, I need to introduce new pore water tracers for NH<sub>4</sub> and NO<sub>2</sub>. Thus far, most pore water tracer indices are matching the ocean tracer indices. Through the use of pre-processor flags, other implemented tracers (solid and dissolved ocean tracers, etc.), etc. this scheme is no longer sustainable and I would like to introduce a mapping between pore water tracers and ocean tracers. This primarily affects `mo_param1_bgc.F90` and `dipowa.F90`.

My current thought is to implement something along the lines (in `mo_param1_bgc.F90`, sort of pseudo-code):
```
int map_por2octra(-1:npowtra)
map_por2octra(ipowaox) = ioxygen
```
and then in `dipowa.F90` using the mapping vector instead of the direct index for the sediment tracer, roughly:
Instead of `iv_oc = iv` using `iv_oc = map_por2octra(iv)` (for most of the tracers that are directly handled via the tredsy).

I will implement this and test this in the master branch (since it shouldn't change the response). If you have a better suggestion how to handle the mapping, please let me know (asap, since I need this part of code soon in the nitrogen cycle). In the course of this, I will also modify (re-order) the sediment tracer index part in `mo_param1_bgc.F90` and make its style similar to the ocean tracer index declaration (and initialization).

**Comment by TomasTorsvik** [comment]
Hi,
I agree that some kind of mapping between ocean tracers and pore water tracers is necessary, the current scheme is not suitable to handle multiple preprocessor flags.

One option perhaps would be to implement a solution similar to what is already done for `ocetra` and atmosphere indices, definig `npowtra` as a sum of base, cisonew and nirtogen partial sums. Then in a separate subroutine do

```
int map_por2ocetra(npowtra)
if (ipowaox > 0) map_por2ocetra(ipowaox) = ioxygen
```

Then we don't need to include the `-1` indices, but I don't see how to implement this directly in the data definition part of the `mo_param1_bgc.F90` module.

**Comment by jmaerz** [comment]
What I have thus far is (and similar for the sediment solid components - without the mapping, of course):
```
     ! sediment pore water components
     ! pore water tracers, index should be the same as for ocetra
      INTEGER, PARAMETER :: i_pow_base=7
      INTEGER, PARAMETER :: ipowaic=1,                                  &
     &                      ipowaal=2,                                  &
     &                      ipowaph=3,                                  &
     &                      ipowaox=4,                                  &
     &                      ipown2 =5,                                  &
     &                      ipowno3=6,                                  &
     &                      ipowasi=7
#ifdef cisonew
      INTEGER, PARAMETER :: i_pow_cisonew = 2
      INTEGER, PARAMETER :: ipowc13=i_pow_base + 1,                     &  ! C-isotope indices do NOT correspond to ocetra!
     &                      ipowc14=i_pow_base + 2                         ! C-isotope indices do NOT correspond to ocetra!
#else
      INTEGER, PARAMETER :: i_pow_cisonew = 0
      INTEGER, PARAMETER :: ipowc13 = -1,                               &
     &                      ipowc14 = -1  
#endif
      INTEGER, PARAMETER :: npowtra = i_pow_base + i_pow_cisonew
      
     ! Mapping between pore water and ocean tracers needed for pore water diffusion
      INTEGER, SAVE      :: map_por2octra(-1:npowtra)
   
      contains

      subroutine init_por2octra_mapping()
        ! this can be done for all pore water tracers irrespective if they are active or not
        map_por2octra(0)       = -9999 ! never be used
        ! base tracers  
        map_por2octra(ipowaic) = isco212 
        map_por2octra(ipowaal) = ialkali 
        map_por2octra(ipowaph) = iphosph 
        map_por2octra(ipowaox) = ioxygen 
        map_por2octra(ipown2)  = igasnit 
        map_por2octra(ipowno3) = iano3 
        map_por2octra(ipowasi) = isilica  
        ! either goes into the -1 (and never touched) or into the used index
        map_por2octra(ipowc13) = isco213 
        map_por2octra(ipowc14) = isco214 
      end subroutine init_por2octra_mapping
```
The initialization via the subroutine (called in `hamocc_init.F90`) is required since module don't allow it directly. I am uncertain about the `-1`  indices, though - maybe your solution is more reader friendly.

**Comment by JorgSchwinger** [comment]
Yes I agree this is a good idea. I don't immediately see the purpose of having the index of `int map_por2octra(-1:npowtra)` starting at -1? Shouldn't the field just map the indices for each the `npowtra` sediment tracer to exactly one ocaen tracer?

**Comment by jmaerz** [comment]
Ok, I guess I then go for Tomas solution (using if statements) to enhance readability.. The `-1` was thus far thought as an unused dummy for any unused pore water tracer that doesn't need matching - `map_por2octra(-1)` and `map_por2octra(0)` will/would never be used during run time.

**Comment by JorgSchwinger** [comment]
One could just implement this as a static parameter array, without need to initialize it? Is there an advantage of having the initialization routine?

**Comment by jmaerz** [comment]
The readability and clarity is the advantage, I would say - particularly, if you have (multiple) pre-processor flags.... - there is not much worry about the right order then.

**Comment by JorgSchwinger** [comment]
There would be no pre-processor flags needed (ocean tracers indices of tracers that do not exist are set to -1). Readability would depend on how it is written, and it would not require initializing anything. Since it's not supposed to change frequently, it would be okay to have it in this 'hard-coded' fashion.

But I also have no strong opinion against the other solution. I just find it more complicated than necessary.

**Comment by jmaerz** [comment]
You need a different list of indices for each combination of pre-processor flags switched on (note my future introduction of another PP-flag), if I am not mistaken. Second, with the dynamic subroutine version, we are going more into the direction of dynamic, non-static mapping which is re-usable, once we dynamically allocate the number of ocean tracers (had also just a discussion in real with @TomasTorsvik). But I am agnostic on these things - I just want to avoid another if statement in `dipowa.F90` with my extended nitrogen cycle.

**Comment by TomasTorsvik** [comment]
I was just about to comment, but @jmaerz beat me to it ...

I think doing the mapping in a separate initialization routine is a more flexible solution. While it is true that we don't change these indices very often, I think it is still valuable to accommodate for for future changes, preferably without adding more preproessor flags than necessary.

**Comment by jmaerz** [comment]
@TomasTorsvik and @JorgSchwinger , can it be that there is a bug for C13,C14 (+ natDIC) in the master `dipowa.F90`, l. 213,217,220 and `ocetra(i,j,kbo(i,j),iv)` should read instead `ocetra(i,j,kbo(i,j),iv_oc)`? - since at present state, it checks against wrong ocetra for these? - I guess, I am asking more for a confirmation than for whether it is wrong...

**Comment by TomasTorsvik** [comment]
Ye, this looks wrong, although the bug would only become apparent if `cisonew` is enabled.

**Comment by jmaerz** [comment]
Ok, I have set up a branch `map_por2octra` in my BLOM fork. I'll test it against the former master and check whether the sediment is bit-identical. If you confirm the bug with the tracer indexing, I would suggest to first pulling in the new mapping into `master` (since I started from master), then merging master again into the `beyond-CMIP6` branch and I fix the bug in the `beyond-CMIP6` branch. @tomas, I agree, this only affects the PP-enabled `cisonew`.

**Comment by jmaerz** [comment]
Whom else to inform about that issue?

**Comment by tomas** [comment]
@jmaerz please don't mention me again in this repository. I have nothing to do with this

**Comment by jmaerz** [comment]
I just realize that #26 might be (in parts) related to that bug.

**Comment by JorgSchwinger** [comment]
> 

In line 217 this is bug - thanks for spotting this. It has come in there only with the sediment acceleration scheme, and it would affect only the diagnostic output. But good if it is corrected.

The other lines are actually correct as they are. This is a workaround anyway, because we didn't want to implement the natural DIC and alkalinity through the whole sediment module. (some kind of explaining comment on this would have been nice...

**Comment by jmaerz** [comment]
Hi @JorgSchwinger , ok, I guess, I see your point, while you meant line no. 213 being a bug, right? Maybe it is then worth rewriting that part a bit, as in:
`if (iv==ipowaic)...ocetra(,iv->isco212)`
and similarly for alkalinity, which could be done, when fixing the bug in a next step. For now, I didn't touch this potential bug in the pull request #192 since I wanted to do this afterward in an additional step.

**Comment by jmaerz** [comment]
After reading and commenting on #192 https://github.com/NorESMhub/BLOM/pull/192#discussion_r963987178 , I guess, as suggested there, we can do the exchange of indices immediately. Question remains about the slightly changed writing as suggested above.

**Comment by JorgSchwinger** [comment]
Regarding the writing, both are possible I guess, but I would prefer
`if (iv_oc==isco212)   ocetra(i,j,kbo(i,j),inatsco212) = ...`
Otherwise the correspondence between isco212 and inatsco212 is lost.

**Comment by jmaerz** [comment]
Hi @JorgSchwinger , mmmh, we can do this, but then you need to look up in `mo_parm1_bgc.F90`, to which pore water tracer `iv_oc==isco212` refers to (after putting in the mapping). With 
```if(iv==ipowaic) ocetra(...inatsco212)=ocetra(...,inatsco212)+ocetra(...,isco212)-aprior```
, it would be very obvious. But  up to you - whatever you prefer.

**Comment by jmaerz** [comment]
Ok, I updated the code according to your suggestions and will test it.

**Comment by jmaerz** [comment]
Hi @TomasTorsvik and @JorgSchwinger , as you might have seen in https://github.com/NorESMhub/BLOM/pull/192#issuecomment-1239193348 , I tested the code and results are identical. Do you have further suggestions, comments wrt the made code changes?

**Comment by TomasTorsvik** [comment]
Hi @jmaerz , I have no further comments to the PR, so you have a green light from my side.
