### ISSUE TITLE
iHAMOCC: Bugfix for sediment alkalinity needed?

### ISSUE THREAD

**Issue by jmaerz** [NorESMhub/BLOM#193]
Currently, in both the CaCO3 carbon cycle calculation, l. 429:
```Fortran
alk = (powtra(i,j,k,ipowaal) - (anaerob(i,k)+aerob(i,k))*16.)  / rrho
```

and the update of alkalinity, l.  539-540
```Fortran
powtra(i,j,k,ipowaal) = powtra(i,j,k,ipowaal)                       &
                &   + 2. * posol * umfa - 16. * (aerob(i,k) + anaerob(i,k))

```
in `powach.F90` of `feature-hamocc_beyond-CMIP6` (and thus also in `master`) the alkalinity is probably updated in the wrong form, or is, at least, inconsistent with the way, how alkalinity is handled in `ocprod.F90`. In both code snippets, `aerob(i,j)` is the aerobically and `anaerob(i,j)` the anaerobically ('denitrification' and 'sulfate reduction' ) remineralized amount of organic phosphorus.

In `ocprod.F90`, the alkalinity change due to aerobic remineralization (and sulfate reduction) is 
```Fortran
 ocetra(i,j,k,ialkali) = ocetra(i,j,k,ialkali)-(rnit+1)*remin
```
For denitrification, it is
```Fortran
ocetra(i,j,k,ialkali) = ocetra(i,j,k,ialkali)+(rdnit1-1)*remin-remin2o
```
where in both cases, `remin` is (as in the sediment `aerob` and `anaerob`) in phosphorus units, `rnit=16` , `rdnit=0.8*ro2ut-rnit=0.8*172-16=121.6`. 

Hence, I think, the **alkalinity changes in the sediment need to be rewritten** as (l.429):
```Fortran
alk = (powtra(i,j,k,ipowaal) - ((sulf(i,k)+aerob(i,k))*(rnit+1.) + anaerob(i,j)*(rdnit-1.))/ rrho
```
and (l.539-540):
```Fortran
powtra(i,j,k,ipowaal) = powtra(i,j,k,ipowaal)                       &
                &   + 2. * posol * umfa - (rnit+1) * (aerob(i,k) + sulf(i,k)) + anaerob(i,j)*(rdnit-1.)
```
where `sulf` needs to be introduced (or we update `aerob`, while this would be misleading in the naming) as the anaerob sulfate remineralization, while `anaerob` only holds the denitrification. 

**What do you think**, @JorgSchwinger and @TomasTorsvik? 

If we/I fix fix the potential bug, where to push it best (`master` or `feature-hamocc_beyond-CMIP6` - the sediment was witched off for the CMIP6 experiments, right?)? I would also exchange the hard-coded numbers by `rnit`, ...

**Comment by JorgSchwinger** [comment]
I agree with your analysis. Some time ago we changed rnit -> (rnit+1) and corrected (hopefully) the stochiometry of denitrification in ocprod, but these changes were never carried over into the sediment code. So it would be excellent to change this.

This should go into the beyond-CMIP6 branch (the sediment code was switched on in CMIP6, so these changes will break backwards bit-for-bit reproducibility).

**Comment by jmaerz** [comment]
Hi @JorgSchwinger , ok, thanks for the swift response! Then I am going to prepare a branch and pull request (both based on `beyond-CMIP6`) for this the next days.

**Comment by jmaerz** [comment]
Hi @JorgSchwinger and @TomasTorsvik , I added `sulf13,14` to the code to reflect the code changes done for 12C. However, now I stumbled over the stoichiometric values in the denitrification part of `powach.F90` again, when looking at the NO3 consumption and N2 production. To my understanding, these values need to be changed as well:
 
For NO~3~: `98` -> `rdnit1` (which is 121.6)
and for N~2~: `57` -> `rdnit2` (which is 68.8 = 121.6/2+16/2, energy requirement and POM degradation)
Further, when calculating `posol`, we need to divide by `2.*rdnit2` instead of `114` (=`2*57`).   

I'll add this and would merge it, if you agree.

**Comment by jmaerz** [comment]
@JorgSchwinger and @TomasTorsvik , I am a bit puzzled about these lines -only present- in aerobic remin and denitrification
```
 ! is this correct? no corresponance in the lines above
 powtra(i,j,k,ipowc13) = powtra(i,j,k,ipowc13) + poso13*umfa
 powtra(i,j,k,ipowc14) = powtra(i,j,k,ipowc14) + poso14*umfa
```
To my understanding, the `powtra` are updated twice due to these lines, since in l. 543-550, part `Calculate updated degradation rate from updated undersaturation`, the 13,14C are again updated via the `aerobic13,14` and `anaerobic13,14` fields. I would therefore suggest to delete these lines for aerobic remin and denitrification.

**Comment by jmaerz** [comment]
@JorgSchwinger and @TomasTorsvik , in general, I feel it would be good to merge `master` into the `beyond-CMIP6` branch either before (then I will handle merge conflicts) or directly after (then somebody else or me handles the merge conflicts) due to the recent sediment porosity implementations in `master`. I think that after these changes, the isotope code should be up-to-date in the sediment.

**Comment by TomasTorsvik** [comment]
> in general, I feel it would be good to merge `master` into the `beyond-CMIP6` branch either before (then I will handle merge conflicts) or directly after (then somebody else or me handles the merge conflicts) due to the recent sediment porosity implementations in `master`.

I agree with this. I tend to think that it is better to merge `master` to `beyond-CMIP6` before merging in a new code change. This way you can resolve potential conflicts between `master` and the old `beyond-CMIP6` in a separate step (hopefully there should not be any), before creating a new `beyond-CMIP6`. If you do it the other way around, it may be more difficult to untangle if a conflict with `master` is due to the old `beyond-CMIP6` or the new code changes. It's a minor point, either way should work I guess.

**Comment by JorgSchwinger** [comment]
Thanks for taking care this, Jöran. The sediment isotope code was never really finished (the model has not been tested with C-isotopes and sediments switched on). So it is well possible that there are still errors (i.e. I would agree deleting the lines of code mentioned above).

Regarding the stochiometry, I did the update of the water-column part with help of Iris (Kriest), so I hope the water column part is correct. If the sediment is inconsistent with this, would be great to fix this (I can't really judge the details right now without diving deeper into the code - I trust your suggestions are correct).

**Comment by jmaerz** [comment]
@JorgSchwinger and @TomasTorsvik , I made the code changes and would now be ready to merge with the `beyond-CMIP6` branch. I just spoke to Tomas, who will merge master into the feature branch before I do the merge, since I know from a local test that it will result in merge conflicts.

**Comment by jmaerz** [comment]
After merging the master into `beyond-CMIP6` branch, I resolved any conflicts and the bug-fixing branch is ready to be merged into `beyond-CMIP6`.

**Comment by jmaerz** [comment]
Merged.
