### ISSUE TITLE
Fix required for spatially variable porosity for case `sedbypass=true`

### ISSUE THREAD

**Issue by jmaerz** [NorESMhub/BLOM#197]
Hi @TomasTorsvik and @JorgSchwinger , unfortunately, I overlooked the case  `sedbypass=true` when implementing the spatially variable porosity. Thus far, we ONLY allocate memory for `porsol`, `porwah`, `porwat`, `solfu` and the diffusion coefficients, when `sedbypass=false`. However, during the initialization process, `bodensed.F90` is called irrespective of this and we are trying to fill un-allocated fields, when `sedbypass=true`. Formerly, these fields were 1D and always allocated, while we actually don't need them really, when `sedbypass=true`. 

So, (quick) question: shall we always allocate the 2D and 3D fields or do you feel it is better to only fill them in `bodensed.F90` during the initialization, when needed (meaning: we ignore filling them, when `sedbypass=true` via pre-processor flags in `bodensed.F90`). I see the trade-off between memory usage versus readability here... - which is why I am asking.

**Comment by JorgSchwinger** [comment]
I would go for a pre-processor flag in bodensed. Is it necessary at all to call bodensed in the case the sediment is deactivated? If not the pre-processor flag could go into hamocc_init.

**Comment by jmaerz** [comment]
Well, I am aware that the aggregation scheme (Iris & mine) uses some parameter(s) from the sediment module, which are initialized in `bodensed`, so in the present state, we cannot simply switch it off in `hamocc_init`. I can re-arrange `bodensed` a bit to have a part with purely parameter settings and a part with the writing of allocated fields which then can be switched off - it would be the pre-step to put `bodensed` into `mo_sedmnt` completely (having there then two subroutines - parameter initializations and field fillings).

**Comment by JorgSchwinger** [comment]
Sounds good to me.

**Comment by jmaerz** [comment]
Ok, as quickly discussed in real, I'll split it up and move the routines into `mo_sedmnt`. I'll try to get that done early next week.
