### ISSUE TITLE
Units of dust/clay in iHAMOCC output

### ISSUE THREAD

**Issue by jmaerz** [NorESMhub/BLOM#211]
Hi @JorgSchwinger an @TomasTorsvik , to my understanding, the output units related to clay/dust (`ifdust`/`ssster`) should be kg  (or g, depending on the factor involved) instead of mol (so e.g. kg/m3, ... instead of mol/m3). Any calculation done for dust and clay material seems to be/are done in units of kg/m3 (see e.g. iron-input `mo_apply_fedep`, where dust input is applied or `mo_sedmnt`, where the clay factor `clafa` is calculated). If I am correct, shall we put this into the NorESM2.0.6 version?

**Comment by JorgSchwinger** [comment]
I haven't followed through the whole code, but if you are sure that the output units aren't correct, it would be nice to change it.
I think the water column dust tracer is not in the output.

**Comment by TomasTorsvik** [comment]
We can still update the `release-1.3` branch, so technically this can be included in NorESM2.0.6. Suggest to use te same procedure as we did for the pnetcdf bug fix (#208, #209).
