### ISSUE TITLE
Units in iHAMOCC restart file

### ISSUE THREAD

**Issue by jmaerz** [NorESMhub/BLOM#238]
@JorgSchwinger and @TomasTorsvik: looking into `aufw_bgc.F90`, I think the units for `ssster` and `bur_clay` should be `kg/m**3` and `kg/m**2`, respectively (both similar to the unit fixes introduced in #213 - I missed the restart file writing in #213). Additionally, `satoxy` should be   `Saturated oxygen` in `mol O2 kg` (currently handled as `xxx..`). I am not sure, if it would break any run cases (and automatic reading of restart files) though.

**Comment by TomasTorsvik** [comment]
Hi @jmaerz , as far as I know, the only string variable used when reading restart files is the variable name itself, so I don't foresee any problems with changing the units in the output files.

**Comment by JorgSchwinger** [comment]
I'm also pretty sure that the units in the file serve no purpose other than descriptive (they are not read during restart). So it should be fine to use correct units.

**Comment by jmaerz** [comment]
Ok, then I will draft a fix to `master` since it is not answer changing. If you see this differently, please object.
