### ISSUE TITLE
Bug fixes for C14 isotopes

### ISSUE THREAD

**Issue by JorgSchwinger** [NorESMhub/BLOM#26]
There are a few bug fixes for C14 isotopes that have not yet been included in the main code.  Anne Moree has developed and tested the code. The fixes can be found in  /cluster/projects/nn2980k/Moree/NorESM2/cases/NOINYOC_tn21_18d/SourceMods/. Note that these runs are based on the BCCR-fast version of NorESM1, so care has to be taken when implementing this in NorESM2.

**Comment by TomasTorsvik** [comment]
@JorgSchwinger 
Any idea when this can be done? I don't find  /cluster/projects/nn2980k/Moree on either Fram or Betzy. Do you have the sourcemods somewhere else, or maybe we need to contact Anne?

**Comment by JorgSchwinger** [comment]
I should have this somewhere, have to check. I can do this, but it's busy at the moment, so I'll need a bit of time.

**Comment by TomasTorsvik** [comment]
Actually, we have a backup of Anne's project directory from Fram, copied to Nird under `NS2980K/backup/Moree/Fram_nn2980k/NorESM2.tar.gz`, so I guess we have the sourcemods.
