### ISSUE TITLE
Implement C-isotopes in sediment code

### ISSUE THREAD

**Issue by JorgSchwinger** [NorESMhub/BLOM#27]
The new C-isotope code of NorESM has to be coupled to the sediment. Currently the code can only be run with -Dsedbypass

**Comment by jmaerz** [comment]
Hi @JorgSchwinger , what was/is the reason for the lack of this capability? I am asking also with regards to #193 and #194.

**Comment by JorgSchwinger** [comment]
The reason was that it was never really finished. Anne Morée did the implementation in the water column, but didn't touch the sediments. I think (if I remember correctly) Christoph started to do the sediment part, but this was never finished/tested. So if you have gone through all sediment and think it's correct, that's great (and would close this issue after some testing has been done).

One would have to think a bit about the initialization of the C-isotope sediment part (for the water-column Anne and I developed some nice initialization scheme that worked quite well). We can discuss this at some point (maybe also with Christoph).

**Comment by jmaerz** [comment]
Ok, thanks for the information. Since I have never worked with -modelling- isotopes, I cannot judge on the initial equations, but from a code perspective, I would consider the code parts that I have looked at as clean(er)/correct. I guess, for now, I keep this information on my mind and will take another look the next days, while I would like to finish #193 and #194.

**Comment by jmaerz** [comment]
Half of a reminder to myself, half as discussion: in `sedshi.F90`, the upward shifting from the burial layer into the active sediment layer only considers refilling of non-isotopes, while afterward, all solid sediment tracers experience upward re-distribution. Isn't there a re-filling also needed from the burial for isotopes? - or am I missing something?

**Comment by TomasTorsvik** [comment]
@JorgSchwinger 
Can we close this as well now?

**Comment by JorgSchwinger** [comment]
I wanted to commit one more correction for the 1.4 release (once the ifdefs/namelist PR is merged), but in general this is done, so it can be closed.

**Comment by jmaerz** [comment]
Hi @JorgSchwinger (cc @TomasTorsvik), your commit was done, right? - so that we can close this issue?

**Comment by JorgSchwinger** [comment]
Yes, I close this now.
