### ISSUE TITLE
cannot run ERP test with BLOM

### ISSUE THREAD

**Issue by mvertens** [NorESMhub/BLOM#270]
The ERP test checks to see if a restart run is bit-for-bit even though the PE count is halved. The problem is that BLOM can only run on a fairly limited set of PEs - and just halving the PEs will not work.
As an example - the following test ERP_Ld3.T62_tn14.NOINY.betzy_intel using the PE-layout 
```
CPL :     96/     1;      0      1
ATM :     96/     1;      0      1
LND :     96/     1;      0      1
ICE :     96/     1;      0      1
OCN :    256/     1;     96      1
ROF :     96/     1;      0      1
GLC :     96/     1;      0      1
WAV :     96/     1;      0      1
ESP :      1/     1;      0      1
```
built with no problem for the first phase. 
But when the second phase - which halves the processor count - tried to build - the following error occurred in BLOM:
```
err=blom_dimensions: Cannot find patch.input file for 128 processors!
blom_dimensions: Available processor counts: 32 42 63 77 91 123 156 186 256 354
```

So one possibility is to generate a 128 processor count capability for BLOM just so that the out of the box test with 256 pes can run. But this would only work if 256 pes were used for the first phase. For now the ERP test will be backed out in favor of an ERS test until this issue can be resolved.

**Comment by monsieuralok** [comment]
@mvertens Can not we change processor count for BLOM in test suite to 123 ? Where Can I check ERP test and How those are configured?

**Comment by mvertens** [comment]
@monsieuralok - I think that will be tricky to dp. The test itself is generic and is part of the CIME case control system (CCS). There is no functionality right now to have the first and second phase have specific processor counts. 
If you check out CIME 
> https://github.com/NorESMhub/cime
> cd cime/CIME/SystemTests
You can look at erp.y in that directory (or any of the other tests for that matter).

**Comment by monsieuralok** [comment]
@mvertens I have created one with 128 PE on Betzy: /cluster/projects/nn9560k/alok/mapping_alok/mapping/Partit/patch.input.128 You can commit it to BLOM and test.  Usually, it should work but BLOM also checks internally few things that can reject it.

**Comment by mvertens** [comment]
@monsieuralok - Great! thanks so much. I'll test this and let you know.

**Comment by mvertens** [comment]
@monsieuralok - that worked and the ERP test now passes for BLOM without HAMOCC. Thanks so much! I'll add this file into my PR for the namelist regeneration.
