### ISSUE TITLE
DEBUG compile option fails on Betzy due to iHAMOCC error

### ISSUE THREAD

**Issue by AleksiNummelin** [NorESMhub/BLOM#271]
Not sure if this is a know issue, but is seems that with the current master I can't use the debug=TRUE option in the env_build.xml as the compilation fails with

components/blom/hamocc/mo_param1_bgc.F90(264): error #5561: Subscript #1 of the array MAP_POR2OCTRA has value -1 which is less than the lower bound of 1

the actual lines giving this error are
if(ipowc13 > 0) map_por2octra(ipowc13) = isco213
and
if(ipowc14 > 0) map_por2octra(ipowc14) = isco214

As mentioned this happens after checking out the current master and I creating a case with 

./cime/scripts/create_newcase --case ../cases/n1850_09_tn14_pacemaker_test_27082023 --compset N1850 --res f09_tn14 --machine betzy --project nn9869k --user-mods-dir cmip6_noresm_hifreq

Any insight would be appreciated, thanks!

**Comment by JorgSchwinger** [comment]
Hi Aleksi, please see here: #254, this has been solved in #256. I assume you must be using not the latest version of master but some release tag?

**Comment by AleksiNummelin** [comment]
Okay, thanks, yes, I was just using the NorESM master, not BLOM master, so known issue in away. Closing this then.
