### ISSUE TITLE
Constituent budget output

### ISSUE THREAD

**Issue by JorgSchwinger** [NorESMhub/BLOM#29]
Clean up, re-organise and extend the inventory routine to give a full budget of all important constituents (taking into account all in- and out-fluxes). Create annual netCDF output for the inventory, which replaces the text-output in the ocean log-file.

**Comment by TomasTorsvik** [comment]
@JorgSchwinger 
I see there is some duplication of code in this subroutine, but I don't know what other constituents to add. Also, should the annual netCDF output be part of the "inventory_bgc" subroutine, or should this be in a separate subroutine?

**Comment by JorgSchwinger** [comment]
The most important thing would be to handle the net in- and outflux from the sediment correctly (this functionality should actually be there already). As to new constituents we need to think how to handle river-input and nitrogen deposition. These fluxes need to be considered if we want to close the budget. Regarding netcdf-output: I'm not sure what the best solution is, also the question, should the output go into the normal annual files or some extra files? Let's discuss this at our next meeting.

**Comment by TomasTorsvik** [comment]
PR #143 implements netCDF output, river input and nitrogen deposition.
