### ISSUE TITLE
Continuous regression testing with NorESM 2.0.6

### ISSUE THREAD

**Issue by jmaerz** [NorESMhub/BLOM#306]
Hi @mvertens , I pull over the discussion from #294 on how to set up a regression testing for HAMOCC/NorESM 2.0.6 into a new issue, since it might be relevant also for others (see also https://github.com/NorESMhub/BLOM/wiki/BLOM-iHAMOCC-regression-testing-with-NorESM and #288) and would easily get buried in the former PR. 

Since the automatic regression test failed when using NorESM 2.0.6, I followed your suggested step to update the file
 `$SRCROOT/cime/config/cesm/machines/config_machines.xml` by replacing the CCSM_CPRNC block under the betzy machine as follows:
```
 <machine MACH="betzy">
       ......
    <CCSM_CPRNC>UNSET</CCSM_CPRNC>
```
with
```
    <CCSM_CPRNC>/cluster/shared/noresm/tools/cprnc/cprnc</CCSM_CPRNC>
```
I did this and now hitting another error:
```
/cluster/shared/noresm/tools/cprnc/cprnc: error while loading shared libraries: libnetcdf.so.19: cannot open shared object file: No such file or directory
```
Any suggestion on this?

**Comment by mvertens** [comment]
@jmaerz - there is a new PR coming into the noresm2.1 CIME today that should hopefully fix these problems for Noresm2.1.
Let me give it a try and make sure it works and then I'll point you to it.

**Comment by jmaerz** [comment]
All fine - this is not too urgent - I just thought it would be good to get that going at some point (and if I understand correct, this will be soon obsolete anyway with NorESM2.1, since there it then functions as expected after your new PR).

**Comment by mvertens** [comment]
So I have a bug fix for mo_ocprod.F90 and mo_bgc_params.F90 that is still bfb. Its not too invasive and also involves formatting changes. I'm wondering if it would be okay to just add it to this PR - since its not very big and would fix the github actions tests. Thoughts?

**Comment by mvertens** [comment]
@jmaerz - this bug fix is implementing what we talked about last night.

**Comment by jmaerz** [comment]
I guess, I pull this discussion over to #305 and answer there to keep it a bit organized :-)

**Comment by TomasTorsvik** [comment]
@jmaerz , @mvertens - this issue seems to be resolved and/or outdated. Can it be closed?

**Comment by jmaerz** [comment]
@TomasTorsvik , from my side yes.
