### ISSUE TITLE
Draft v1.4.0 release

### ISSUE THREAD

**Issue by TomasTorsvik** [NorESMhub/BLOM#310]
@matsbn @JorgSchwinger @jmaerz @mvertens 
I have created a draft `v1.4.0` release on `master`:
https://github.com/NorESMhub/BLOM/releases

So far, only including changelog relative to `v1.3.0`. Are there any suggestions for highlights on this release?

This should be the last CMIP6 compatible BLOM/iHAMOCC version.

**Comment by JorgSchwinger** [comment]
Maybe we should add a summary of the most important changes ("Release highlights")? Here is my suggestion (did I forget something important?)

* Major iHAMOCC code re-organization
  * most pre-processor flags ("ifdefs") replaced by logical flags that are read in via namelist
  * all subroutines placed in modules 
  * new module `mo_param_bgc` collects all model parameters and routines for initialization of model parameters
* Major iHAMOCC code style changes (unified indentation, lower-case keywords)
* Added regression testing functionality for BLOM
* New mechanisms to create namelist files (consistent with other NorESM components) through the file `namelist_definition_blom.xml`
* New mesoscale eddy diffusivity options 
* C-isotope code for sediment now technically supported
* Added support for simulating Ocean Alkalinity Enhancement

**Comment by mvertens** [comment]
@JorgSchwinger - this looks good. Thanks for drafting it. I would qualify that the regression testing in BLOM is only functional when run as part of Noresm - not stand-alone blom. Similarly the namelist creation is only implemented for BLOM running as part of Noresm.

**Comment by TomasTorsvik** [comment]
@JorgSchwinger , @mvertens - Thanks for your suggestions! I have included them in the draft release text.
@matsbn , @jmaerz - Anything to add?
If I don't hear back by tomorrow (Friday) afternoon, I will assume this is good to go and created the release.

**Comment by jmaerz** [comment]
Hi @TomasTorsvik , no additions from my side. Thanks for drafting the release!
