### ISSUE TITLE
Release notes for v1.5.0

### ISSUE THREAD

**Issue by TomasTorsvik** [NorESMhub/BLOM#318]
@matsbn , @JorgSchwinger , @milicak , @jmaerz , @mvertens 
Hi,
I have created a v1.5.0 tag and a draft release notes
https://github.com/NorESMhub/BLOM/releases/tag/untagged-18d9c0ca11e0923e06f4

Please leave a comment if you have suggestions for this release.

**Comment by jmaerz** [comment]
Hi @TomasTorsvik , thanks for creating the tag. Depending on from which tag to which tag you describe the changes: <sup>14</sup>C bug fixes were already carried out for the yet CMIP6 compatible version. You could add the bugfix for the burial calculation in the wrapper (time smoothing), though.
