### ISSUE TITLE
Units mismatch/issue for riverine DOC input? - potential bug

### ISSUE THREAD

**Issue by jmaerz** [NorESMhub/BLOM#331]
Hi @JorgSchwinger and @TomasTorsvik ,
I am trying to calculate the riverine input of nitrogen to iHAMOCC. By inspecting `mo_read_rivin`, `mo_apply_rivin` and the input file for riverine input: `/cluster/shared/noresm/inputdata/ocn/blom/bndcon/river_nutrients_GNEWS2000_tnx2v1_20170915.nc`, I see that the units of DOC input are in kmolC/m2/yr. As far as I am aware of, DOC inside iHAMOCC is handled in P-units. In `mo_apply_rivin`, there is no division by 122 (`rcar`), though. Hence my question: are the units in the input-file correct? - and if so - is this a bug (to my current understanding, yes)? 

From global input, it seems that the units in the input file are wrong (if I perceive them as kmolP/m2/yr, I come up with about 4.28TgN/yr via DON, which is in line with some estimates) 

**As conclusion: the current units of DOC in the input file are wrong**

**Comment by JorgSchwinger** [comment]
Looking at the input file, I see that DET units are correctly stated as kmol P m-2 s-1, so my first hypothesis would be that the "P" was accidentally omitted in the units of DOC.

On the other hand, the DOC flux is not very high: ~0.02 Tmol P/year (assuming the input file units should be kmol P) = 2.44 Tmol C/year. Assuming the input file units are correctly stated would give 298 Tmol C/year (for comparison DIC riverine input is 40 Tmol C/year).

Jöran, do you know what the GNEWS estimates are?

**Comment by jmaerz** [comment]
Hi Jörg, we had the same thought in parallel. From the literature, the input file units for DOC should be probably interpreted as kmolP/m2/yr (and not as kmolC/m2/yr) - resulting in pi-Ctrl riverine input of nitrogen:
- global riverine DIN: 25.91 TgN/yr
- global riverine DOC: 4.28 TgN/yr
- global riverine DET: 14.18 TgN/yr

which is roughly in line with literature estimates (e.g. Seitzinger et al. 2010: Global river nutrient export: A scenario analysis of past and future trends. - a calculation for 1970, table 1a gives: DIN: 14, DON: 10.3 and PN 12.4 TgN/yr for 1970). Hence, the input file units for DOC should be updated.
