### ISSUE TITLE
iHAMOCC towards the NorESM2.3 release

### ISSUE THREAD

**Issue by jmaerz** [NorESMhub/BLOM#336]
This issue tracks the steps taken on the iHAMOCC side towards the NorESM2.3 version as requested in:
https://github.com/NorESMhub/NorESM/milestone/4

On the iHAMOCC side, we intend to incorporate:
1. the extended nitrogen cycle (optional)
2. cyanobacteria growth (bluefix) only in euphotic zone (not throughout MLD) as optional (switch `leuphotic_cya`)
3. the M<sup>4</sup>AGO sinking scheme for marine particles (Maerz et al. 2020) as optional 
4. preformed silicate tracer
5. support for BLOM mks units - since #344 default in BLOM
6. online sediment spinup as default
7. #350

Carbon isotopes were already included as optional in the NorESM2.1 release (and they stay optional in NorESM2.3).

Points 1-4 will be included when merging the extended nitrogen cycle into `master` #269 .
Points 5-6 are already included in the `master` of BLOM.

Currently, we aim at merging the `extNcycle-M4AGO` branch into `master` in the last days of May 2024.

**Comment by TomasTorsvik** [comment]
The additions to NorESM2.3 from iHAMOCC is now completed.
