### ISSUE TITLE
 Modifications necesarry after including the M4AGO scheme?

### ISSUE THREAD

**Issue by JorgSchwinger** [NorESMhub/BLOM#351]
Hi @jmaerz, after the M4AGO scheme has been included as a sub-repository, the code doesn't compile out of the box. What are the steps we need to take to make the code compile again? I guess we need to manually modify Externals.cfg?

**Comment by jmaerz** [comment]
Hi @JorgSchwinger , can you briefly describe, what you've done? With a regular:
```
git clone git@github.com:NorESMhub/NorESM.git
cd NorESM
checkout_your_desired_NorESM-version
./manage_externals/checkout_externals
```
it should work (maybe requires  a `module load Python/2.7.18-GCCcore-10.2.0` or similar, depending on the NorESM version used).

**Comment by TomasTorsvik** [comment]
@JorgSchwinger - yes, if your BLOM source code was not updated, you need to add M4AGO manually, as described in the #269 PR:
https://github.com/NorESMhub/BLOM/pull/269#issuecomment-2135787387

This should not be necessary if you start from the latest tag `v1.6.0`.

**Comment by JorgSchwinger** [comment]
I just updated master, which of course doesn't work.

I tried to do a `checkout_externals` on my existing local clone, but  the script would not let me do this (even though everything is clean with no un-commited changes).

I will re-install my local clone. It would be good though to notify everyone working with BLOM on the current master that this will be necessary.

**Comment by jmaerz** [comment]
Hi @JorgSchwinger , let me/us know, how it works out. I am not sure, if there is something like a cime tool that enables to clean up the previous settings (I was running a few times into issues with cime `checkout_externals` when branches/component externals had changed). Shall we document this in the release notes? - or where else?

**Comment by TomasTorsvik** [comment]
@JorgSchwinger , @jmaerz - I had similar problems with the components not updating properly, so I did a clean checkout from source. It is probably a good idea to include a note on this in the release notes, it's more likely that someone will see it there than if it goes as an issue.

**Comment by JorgSchwinger** [comment]
I also did a clean checkout from scratch now, this worked fine.

**Comment by jmaerz** [comment]
Thanks for the confirmation.

**Comment by TomasTorsvik** [comment]
I have added a note on this in the release note draft.

**Comment by TomasTorsvik** [comment]
Closing this, as seems no further action is needed.
