### ISSUE TITLE
How to run BLOM in tagged version v1.6.0 close/identical to the CMIP6 circulation field?

### ISSUE THREAD

**Issue by jmaerz** [NorESMhub/BLOM#354]
@matsbn ,@AleksiNummelin (and @TomasTorsvik , since it might be relevant for your scientific work as well), I have a short question: if one wants to run the current master (as of tag v1.6.0) and would want to get the circulation as close as possible to the circulation represented in CMIP6, I would need to use:
- `./xmlchange BLOM_UNIT=cgs `

and then resetting the eddy parametrization values (looking into both, description and changes made in PR #337) from:
```
EDANIS = .true.
EDDF2D = .true.
EDSPRS = .false.
RHSCTP = .true.
EGC = 3.0
EGMNDF = 1.
EGMXDF = 2500.
RHISCF = 0.5
```
to
```
EDANIS = .false.
EDDF2D = .false.
EDSPRS = .true.
RHSCTP = .false.
EGC = 0.85          ! for tnx1v4 and 0.5 for tnx2v1
EGMNDF = 100.e4     
EGMXDF = 1500.e4    ! for tnx1v4 and 1000.e4 for tnx2v1 
RHISCF = 0.
```
right? - or do I miss something and further things would need to be changed? - would this setting result in identical or only close to CMIP6 circulation? Once answered, it could be added to the v1.6.0 release note https://github.com/NorESMhub/BLOM/releases/tag/v1.6.0

A brief `user_nl_blom` snippet would be greatly appreciated. 

**For tested `user_nl_blom` and correct settings, see:** https://github.com/NorESMhub/BLOM/wiki/new-BLOM-with-CMIP6-settings 

and below: https://github.com/NorESMhub/BLOM/issues/354#issuecomment-2410651675

**Comment by jmaerz** [comment]
@matsbn , I would be grateful, if you could have a look and give advice on how to run the 1.6.x version of BLOM as close as possible to the CMIP6 circulation. If I am not mistaken, @TomasTorsvik and his works would also benefit from this information.

**Comment by TomasTorsvik** [comment]
@jmaerz , @matsbn - yes, I'm also interested in running with BLOM/iHAMOCC `v1.6.x` in a setup that resembles the CMIP6 circulation.

**Comment by matsbn** [comment]
Sorry for my very late response to this. I do believe using ``xmlchange BLOM_UNIT=cgs`` and setting
```
EDANIS = .false.
EDDF2D = .false.
EDSPRS = .true.
RHSCTP = .false.
EGC = 0.85
EGMNDF = 100.e4     
EGMXDF = 1500.e4
RHISCF = 0.
```
should revert to the CMIP6 settings for BLOM when using the tnx1v4 grid. These parameter settings can just be pasted directly in below the comment section of user_nl_blom. Unfortunately, I have not had time to actually test this to remove the "believe" statement and I will not be able to do this the next few weeks (vacation and Betzy maintenance).

The cleanest would probably be that in release branches where we still want the ability to reproduce CMIP6 results, we implement something like a BLOM%CMIP6 option, that will set the correct namelist values, also taking into account grid dependencies. Until time is found to implement and test such a functionality, modifying user_nl_blom is the way to go.

**Comment by jmaerz** [comment]
@matsbn , thanks for the reply - I will give it a try. Should we expect bfb in that case?

**Comment by jmaerz** [comment]
Thus far, I can confirm that running NorESM2.1.3, using BLOM tag version `v1.6.2` via changing the `Externals.cfg`, in combination with the compset `NOINYOC` with grid `T62_tn21` using:

`./xmlchange BLOM_UNIT=cgs`

together with `user_nl_blom` with entries:
```
EDANIS = .false.
EDDF2D = .false.
EDSPRS = .true.
RHSCTP = .false.
EGC = 0.5
EGMNDF = 100.e4     
EGMXDF = 1000.e4
RHISCF = 0.
```
for one month results in bfb results for BLOM, when compared to the NorESM 2.1.3 default version (=> BLOM tag version v.1.5.2). For `T62_tn14`, the `user_nl_blom` needs to read:
```
EDANIS = .false.
EDDF2D = .false.
EDSPRS = .true.
RHSCTP = .false.
EGC = 0.85
EGMNDF = 100.e4     
EGMXDF = 1500.e4
RHISCF = 0.
```
to recover the NorESM2.1.3 default version (tested and resulted in bfb for a 1month run).

**Comment by TomasTorsvik** [comment]
@jmaerz - great, thanks for testing!
It would be useful to make a note on this outside of this issue. I made one in the BLOM wiki
https://github.com/NorESMhub/BLOM/wiki/new-BLOM-with-CMIP6-settings
Maybe there are better options, but it doesn't fit so well in the standard documentation.

**Comment by jmaerz** [comment]
Hi @TomasTorsvik , I suggested to put it into the release notes, but maybe that doesn't fit that well? - I updated the above comment, now for both 2 degree and 1 degree grid, both tested with a 1 month run.

**Comment by TomasTorsvik** [comment]
@jmaerz - yes, I think we can put this in the release notes as well. I would prefer to have it in the release notes for `v1.6.0` which is the more extensive one, and not for each of the minor update releases. I can draft this.

**Comment by jmaerz** [comment]
Also updated your new wiki page for the different `user_nl_blom` required for the different resolutions.

**Comment by TomasTorsvik** [comment]
@jmaerz - actually, I think I will just put a reference to the wiki page in the release notes, so that if something changes, we only need to update one place. Is that OK with you?

**Comment by jmaerz** [comment]
Perferctly fine - closing this issue now.
