### ISSUE TITLE
mo_ihamocc4m4ago.F90 is not checked out with master

### ISSUE THREAD

**Issue by mvertens** [NorESMhub/BLOM#357]
I am trying to merge the latest master into my refactor branch.
To start with I am trying to compile a blom case using master (on derecho) for the following test 
 SMS_Ld1.T62_tn14.NOINYOC.derecho_intel
The code cannot compile because it cannot find mo_ihammoc4m4ago - 
(e.g.   use mo_ihamocc4m4ago, only: alloc_mem_m4ago,init_m4ago_nml_params, init_m4ago_params)
It appears that this file is not being checked out with master.
Am I missing something?

**Comment by jmaerz** [comment]
Hi @mvertens , starting from a fresh master, it should check out as well. It's an external submodule that is needed. See #269 and release notes + most useful source: https://github.com/NorESMhub/BLOM/issues/351- if you need further help, let me know.

**Comment by matsbn** [comment]
To check out submodules without checking out everything from scratch, one could try:
````
git submodule update --init --recursive
````

**Comment by jmaerz** [comment]
```
cd components/blom/pkgs
git clone https://github.com/jmaerz/M4AGO-sinking-scheme.git
```

**Comment by mvertens** [comment]
Thanks @jmaerz and @matsbn - this is super helpful.

**Comment by jmaerz** [comment]
Dear @mvertens , I close the issue as solved (otherwise feel free to open it again, if needed).

**Comment by mvertens** [comment]
Thanks. It all works now!
