### ISSUE TITLE
guidance in interpolating blom 3d temperature and salinity to a set of output levels

### ISSUE THREAD

**Issue by mvertens** [NorESMhub/BLOM#364]
There is new functionality in CISM and DOCN to send the multi level temperature and salinity fields from the ocean to cism.
I'd like to put in place the functionality in the BLOM nuopc cap to do the same thing as is done in DOCN. The key point is that output from BLOM must be obtained on a given set of levels - this is similar to what is done for ISMIP6: 30 levels, spanning between -30 m and -1770 m - that’s basically identical to your approach, with a 30 m offset. To be more specific, the levels are:

   integer, parameter :: nlev_export = 30
   real(r8) :: vertical_levels(nlev_export) = (/  &
        30., 90., 150., 210., 270., 330., 390., 450., 510., 570., &
        630., 690., 750., 810., 870., 930., 990., 1050., 1110., 1170., &
        1230., 1290., 1350., 1410., 1470., 1530., 1590., 1650., 1710., 1770. /)

So this is a very naive question - how can I carry out this vertical interpolation in the BLOM nuopc cap? Its not clear to me where the vertical interpolation is done to go from the blom levels to the diagnostic output levels.
I have done this in the DOCN code where BLOM data is read in.
(In https://github.com/ESCOMP/CDEPS/tree/cdeps1.0.43 the code is in  docn_datamode_multilev_mod.F90 and the file(s) read in  is /cluster/shared/ocn/docn7/MULTILEV/N1850frc2G_f09_tn14_gl4_SMB1_celo.blom.hm.2300.nc.

I think I need to have a function similar to diazlv. Is this correct? Adding @mpetrini-norce here.
I've implemented a new scheme similar to what is done in mod_dia.F90 - and I'll be issuing a PR soon with this new functionality.

**Comment by matsbn** [comment]
My recommendation here would depend on whether we will have this functionality for both the "isopyc_bulkml" (isopycnic with bulk mixed layer) and "cntiso_hybrid" vertical coordinate types.

If we use the hybrid vertical coordinate, we already produce a high-order reconstruction of the vertical profile of temperature and salinity and it should be rather "cheap" to remap this to any levels one wish using calls to "prepare_remapping" and "remap" of mod_hor3map.F90. Then we reuse the already defined reconstruction grid data structure ("recon_grd_struct", same for all tracers) and reconstruction source data structure ("recon_src_struct", specific for each tracer), and define a specific remapping data structure ("remap_struct") for the export levels. I actually want to make use of this approach for remapping all 3d fields to the diagnostic levels when using hybrid vertical coordinate, replacing the use of diazlv of mod_dia.F90. There are certainly some complications to this approach, as the data structures for the vertical grid and reconstruction are only stored in "j-slices" to increase performance and reduce memory use. As it is implemented now, one has to expand remap capability within the "cntiso_hybrid_regrid_remap" routine of mod_vcoord.F90.

For the old isopycnic vertical coordinate ("isopyc_bulkml"), an approach similar to diazlv of mod_dia.F90 might be the straightforward choice. The downside is that it is only a first order accurate interpolation (piece-wise constant reconstruction) which might not be ideal to communicate to CISM. This approach should also work with hybrid coordinate. Maybe something like this can be implemented as a first try?

I would for sure want to help with this, but not sure when time permits.

**Comment by mvertens** [comment]
@matsbn - thanks for your input. That is really helpful.  @mpetrini-norce has been carrying out simulations with the current cap and feels that things look okay. For now we think that the current interpolation algorithm is sufficient for the target science. Would it be okay to then use this for now for both isopyc_bulkml and cntiso_hybrid until we have the time to put a more sophisticated implementation in place?
