### ISSUE TITLE
Runs are slow on betzy

### ISSUE THREAD

**Issue by jmaerz** [NorESMhub/BLOM#369]
Dear @mvertens , @JorgSchwinger , @TomasTorsvik ,
I am not entirely sure, whether this is the best place to ask (but I feel such things could be shared somewhere over a channel amongst sigma2 & NorESM users), but when I am running a simple ocean-only setup for a few years as I have done before, betzy seems to be extremely slow compared to before (as in before the module changes carried out by sigma2). It seems to take a time about 3x longer than usual to run a single year. Did you encounter this as well or am I am doing something wrong after the recent merges to `master`?

**Comment by mvertens** [comment]
@jmaerz - I'm not seeing a slowdown in my runs (which are fully coupled). I think you are using stand-alone blom - right? However, I have found that at least one of the following nodes is problematic on betzy and gives irreproducible results that cannot be repeated between runs: b[4349-4351,4353-4356].
When I exclude these nodes the results reproduce.

**Comment by jmaerz** [comment]
@mvertens : stupid question: how to exclude those nodes? (And how did you figure them out?) Yes, I run standalone-blom NOYNYOC on a 2 degree ocean for testing.

**Comment by mvertens** [comment]
It's not a stupid question at all. You need to have the entry
#SBATCH  --exclude=b3355,b3356,b3357,b3359,b3379,b3382,b3383
to your slurm directives.

**Comment by jmaerz** [comment]
@mvertens , many thanks! - I'll try with the next runs. Is there another page, where one can find those kind of information on potentially corrupted nodes?

**Comment by mvertens** [comment]
@jmaerz - I'm still going back and forth with sigma2 about this. I expect that once they are convinced that there is a problem they'll try to take the nodes out until they are fixed. But they keep saying that by the end of the week betzy will be more stable - so they don't want to do anything yet.

**Comment by jmaerz** [comment]
Dear @mvertens , I sometimes wish there would be a more transparent channel (like some online chat/support channels that could be hosted by sigma2, like mattermost) on those things so that other users can learn from it ... But thanks for letting me/us know here about it!

**Comment by JorgSchwinger** [comment]
Just to add: I have sporadically experienced very slow performance of betzy before (and also yesterday) regardless for coupled or ocean-only runs. It's probably connected to certain nodes, but I have never made the effort to find out (i.e. I have never noted down which nodes were suspicious)

**Comment by jmaerz** [comment]
@mvertens  Just to confirm: removing those nodes brings back the old speed for running the model. Thanks again!

**Comment by jmaerz** [comment]
@mvertens , I just post it here: the latest job was failing with:
```
slurmstepd: error: *** STEP 950729.0 ON b3158 CANCELLED AT 2024-07-12T00:53:53 DUE TO TIME LIMIT ***
```
to me looks like one can add one node more to the list...
