### ISSUE TITLE
BLOM does not compile when threading is turned on 

### ISSUE THREAD

**Issue by mvertens** [NorESMhub/BLOM#373]
In the ERP system test - threading is turned on in the compilation even if the number of threads is 1. In this case, BLOM was not able to compile successfully. The culprit  was mod_nctools.F90. This was with BLOM%ECO. Is anyone running BLOM with the number of threads > 1. Will this work?

**Comment by matsbn** [comment]
BLOM without iHAMOCC used to work well with threads > 1. The recent code with hybrid functionality has a lot of lacking OMP statements for loop blocks. It might work, although not tested, but certainly not efficient. I think there was an effort to fix the OMP statements in iHAMOCC, but not sure about the status. On the machines we have had available, we never experienced a useful speedup with hybrid MPI/OpenMP parallelization as far as I can remember. Still, I think it is worthwhile to have the ability for hybrid parallelization.
