### ISSUE TITLE
Propose creating a new minor release v1.4.2 for noresm2.0.8

### ISSUE THREAD

**Issue by TomasTorsvik** [NorESMhub/BLOM#378]
@matsbn , @JorgSchwinger , @milicak , @jmaerz 
I'm thinking to move the noresm2.0.8 release from BLOM v1.3 to v1.4, which is the last CMIP6 compatible version we made.
I would also like to include some of the regression tests that we have introduced in `master`, excluding the WW3 coupling which is not supported in NorESM2.0.X.
Hence, I propose to create a new minor release `v1.4.2` building on `v1.4.1`, and including some additional regression tests.

**Comment by JorgSchwinger** [comment]
I absolutely support moving to v1.4 for the NorESM 2.0.8 release. I think it was by mistake that v1.3 (instead of v1.4) was used for the NorESM 2.0.7 release. Great to have more regression testing available, too.
