### ISSUE TITLE
In ocn_comp_nuocp.F90, the prefix `!$omp <something openmp>` is used in a non-standard way. 

### ISSUE THREAD

**Issue by mvertens** [NorESMhub/BLOM#379]
For all other OMP calls, the prefix `!$omp <something openmp>` is used. I find it strange that this is not required here. Is this documented somewhere?

_Originally posted by @TomasTorsvik in https://github.com/NorESMhub/BLOM/pull/377#discussion_r1723052983_

**Comment by TomasTorsvik** [comment]
There are 1505 instances of `!$`in the `master` code, 1504 continues `!$omp` and a single instance without this continuation.

The odd one out is [ocn_comp_nuopc.F90; L404](https://github.com/NorESMhub/BLOM/blob/42441cab490063eae2550fd9dec018db317cd7e3/drivers/nuopc/ocn_comp_nuopc.F90#L404).
```
!$    call omp_set_num_threads(nthrds)
```
