### ISSUE TITLE
Wrong time smoothing of forcing when coupling interval is different than daily

### ISSUE THREAD

**Issue by matsbn** [NorESMhub/BLOM#38]
@IngoBethke pointed out an issue of non-conservation when applying time smoothing for coupling intervals shorter than one day. Indeed, the smoothing is hardcoded to only work with daily coupling intervals and it is a bug that smoothing is currently allowed with different coupling intervals.

**Comment by JorgSchwinger** [comment]
But the CMIP6 simulations have been performed with time-smoothing turned off, haven't they?

**Comment by milicak** [comment]
Unfortunately, (as far as I know), as long as you run with leap-frog, time-smoothing is applied.
@matsbn Could you please point out the hard coded part in the code (line etc.).
I couldn't follow it, and also for future references, it would be nice to include this information.

**Comment by matsbn** [comment]
The bug relates to time smoothing of forcing received through the coupler, not filtering of the leap-frog computational mode. We are not using this forcing smoothing in the NorESM2 CMIP6 simulations (1 hour coupling interval, 1 hour ocean baroclinic time step). The problem is in https://github.com/NorESMhub/BLOM/blob/master/cesm/getfrc_cesm.F (line 45) and should be quite easy to fix.
