### ISSUE TITLE
Remove MLD switch for cyanobacteria - making euphotic zone N2 uptake remaining default 

### ISSUE THREAD

**Issue by jmaerz** [NorESMhub/BLOM#395]
Hi @TomasTorsvik, 
I was briefly discussing with @JorgSchwinger about the next steps to be taken towards the iHAMOCC version for NorESM2.5 (as summarized in #340). We introduced those switches for cyanobacteria N2 uptake taking place in either the MLD or the euphotic zone only to enable better technical comparability between the isopycnic and the hybrid coordinates in BLOM. @TomasTorsvik : are they still needed or is this an outdated task and the switch can be removed in favor of cyanobacteria uptake only in the euphotic zone?

**Comment by TomasTorsvik** [comment]
@jmaerz - are you referring to the `leuphotic_cya` switch?
```
          do k=1,merge(kwrbioz(i,j),kmle(i,j),leuphotic_cya) ! if leuphotic_cya=.true., do bluefix only in euphotic zone
```
I think we can  simplify this to `do k=1,kwrbioz(i,j)`

**Comment by jmaerz** [comment]
Yes, that's what we will do eventually - I was just remembering that you had once the incentive to look into the hybrid versus isopycnic coordinates which demanded to have the switch build-in. From your answer, I grasp that we can remove it now again. Thanks.
