### ISSUE TITLE
Step-wise introduction of T-dep. and O2-dep of remineralization?

### ISSUE THREAD

**Issue by jmaerz** [NorESMhub/BLOM#400]
Hi @JorgSchwinger and @TomasTorsvik , as we discussed to move on and enable T-dep. and O2-dependent remineralization (#340): shall we perform this for the default iHAMOCC version in a two-step process (i.e. providing switches, which may then later be removed)?

**Comment by JorgSchwinger** [comment]
Maybe a two step process, but with the clear aim to remove the switch once a longer model run has shown that it behaves as expected?

**Comment by TomasTorsvik** [comment]
> Maybe a two step process, but with the clear aim to remove the switch once a longer model run has shown that it behaves as expected?

Sounds reasonable to me.

**Comment by jmaerz** [comment]
Ok, then we go that route. For now, I suggest that anyone who is providing the switch shall briefly announce it here, before modifying the code so that work isn't done twice. (I likely touch it soon, but don't wanna promise right now.)

**Comment by jmaerz** [comment]
I introduce the switch in #424
