### ISSUE TITLE
Replace DO statements with seared termination (CONTINUE) with DO ... END DO format

### ISSUE THREAD

**Issue by TomasTorsvik** [NorESMhub/BLOM#41]
DO with shared termination was declared obsolescent in Fortran 90, but still part of the Standard. 
Example:
      DO 100 J = 1,NJ
      DO 100 I = 1,NI
      X = X + ARRAY(I,J)
100   CONTINUE

This style still appears in some places in BLOM/iHAMOCC. I would like to replace these instances with the more modern DO ... END DO format.

**Comment by matsbn** [comment]
Yes, I support this. I replaced many do loops in BLOM with termination label in commit https://github.com/NorESMhub/BLOM/commit/ffaf15fa6ce226e5cf0704e306d43ecdf5247465. There might be some left in BLOM and I did not check iHAMOCC.

**Comment by JorgSchwinger** [comment]
This is a good idea. In HAMOCC, the sediment code has many instances of this. Outside the sediment code it is only some loops in ocprod.F90, other routines are not affected. Please check bit-for-bit reproducibility when you do this.

**Comment by TomasTorsvik** [comment]
Tested with NOINYOC_T62_tn21_27 run for 1 year against master. 
There are some deviations in output BGC variables, in particular for the "sss*", with max values

sssc12 = 0.123517459168568 ;

 ssso12 = 0.00157986244893493 ;

 ssssil = 0.262123817857287 ;

 ssster = 15.145099217305 ;

The testing I did was to run to run the current master and my own [refactor branch](https://github.com/TomasTorsvik/BLOM-TTfork/tree/refactor_sediment_code), create a diff on the "NOINYOC_T62_tn21_27_branch.blom.hbgcy.0001.nc" file between the two runs, and did a "ncwa -y max ncdiff_output.nc ncdiff_output_max.nc" to get the maximum values for the diffs.

Sorry this is taking so long, but I think I need to backtrack a bit to see where these differences are introduces.

**Comment by TomasTorsvik** [comment]
PS. If there are more efficient ways to do the comparison, please leave a comment.

**Comment by JorgSchwinger** [comment]
Hi Tomas, could you let me know the location of the output?

**Comment by TomasTorsvik** [comment]
I copied output (archive folders) to Nird
/projects/NS2980K/home/tomast/NorESM/run

latest master version: NOINYOC_T62_tn21_27_master
modified branch: NOINYOC_T62_tn21_27_branch

**Comment by JorgSchwinger** [comment]
Hi Tomas
I checked the output, and I think it looks okay. If you open the diff with ncview you will see that it seems to be roundoff. E.g. ssster is about 2e+6, so a difference of 15 is not much. Keep in mind that we are using compressed 2byte storage, therefore, once a roundoff difference has occurred, an additional difference is introduced during compression (scale factor and offset are slightly different). This can make the difference look unlike roundoff error (i.e. a smooth pattern where one would expect statistical noise). This is the case for some variables, e.g. ppint, but the difference is tiny (5e-18 for a field with order of magnitude 1e-7).

I think you could go on and run this for 100 years, then make time series of global totals (I can provide a matlab script). If these timeseries do not diverge, it is fine. 

We have certainly no bit-for-bit reproducibility any longer after this change.

**Comment by TomasTorsvik** [comment]
Thanks for the feedback @JorgSchwinger !
So you propose that I should do a 100 year run both for master and the feature branch, and make a comparison of global totals?
I guess I don't need monthly outputs, so I should probably change the setup / run script a bit.

**Comment by JorgSchwinger** [comment]
Your master should be bit-identical to NOINYOC_T62_tn21_27 as long as you can run on fram. Also the output for the 2 degree ocean only is not huge, so you could just use the standard output

**Comment by TomasTorsvik** [comment]
By the way, @matsbn ,there is still one instance of a DO ... CONTINUE that I did not touch, in the "mod_xc_sm.inc" file, line 1330. However, this is not actually a shared termination (only terminating a single un-nested do block), so perhaps it is not so important.

**Comment by matsbn** [comment]
I think it is important to consider whether you expected a change in answers with your code modifications. If the code change is merely to replace termination labels with "end do", then there should not be any change in answers and bit-reproducibility is a useful measure of correct implementation. Of course it is not always as simple as this.

In BLOM I use routines chksum and chksummsk that output check sums of fields being modified in a subroutine. Then it is easier to identify where a change occurred. I am not sure this is practical to make use of in iHAMOCC, but it has helped me a lot.
