### ISSUE TITLE
remove branch "feature-hamocc_beyond-CMIP6"?

### ISSUE THREAD

**Issue by TomasTorsvik** [NorESMhub/BLOM#415]
Can we remove the branch `feature-hamocc_beyond-CMIP6`? It seems to be redundant, since new development is merged to the `master` branch.

Last commit on `feature-hamocc_beyond-CMIP6` was Nov 21, 2023;
SHA: 01965250056ace0c67386677245f887104ea088e

**Comment by jmaerz** [comment]
Hi @TomasTorsvik , thanks for the initiative to clean up. From my side, I don't see a good reason to keep it.

**Comment by TomasTorsvik** [comment]
Branch `feature-hamocc_beyond-CMIP6` has been removed.
