### ISSUE TITLE
setting lTO2depremin namelist entry via user_nl_blom does not work

### ISSUE THREAD

**Issue by JorgSchwinger** [NorESMhub/BLOM#428]
Setting the lTO2depremin namelist entry via user_nl_blom does not work, the build script stops with the following error:

`ocn_in_paramgen.OcnInParamGenError: Variable 'lto2depremin' not found in any namelist definition files. Please double-check 'user_nl_blom'.`

Apparently, the mixed upper and lower case writing of the namelist entry seems to be a problem, since the upper case letters are removed. Is this a known problem @mvertens ?

I changed the definition in `namelist_definition_blom.xml` to be all lowercase, which worked. So I propose to use this solution as a workaround (I will issue a PR in a moment), although I think that mixed upper/lowercase writing of namelist entries should be supported.

**Comment by mvertens** [comment]
@JorgSchwinger - I believe this is a current restriction of paramgen. I've assigned the issue to myself and will try to look further into it. I agree that you should be able to use mixed case.
