### ISSUE TITLE
Create feature_GPU_channel2 branch for GPU hackathon

### ISSUE THREAD

**Issue by TomasTorsvik** [NorESMhub/BLOM#51]
@matsbn , @monsieuralok , @AleksiNummelin 

Hi,
I made a copy of the feature_channel2 case based on the path that Alok provided us (see [https://github.com/TomasTorsvik/BLOM-TTfork/tree/feature_GPU_channel2](https://github.com/TomasTorsvik/BLOM-TTfork/tree/feature_GPU_channel2)). I have included most of the files, also some that have intentionally been left out by Aleksi earlier, but I was not able to include two netCDF files from the "regions_and _indices" folder. Maybe there is some trick to include large binary files in gitHub, but perhaps there are better options around for sharing these files?

If this looks OK for you, I can create a corresponding feature branch in the BLOM repository.

-Tomas

**Comment by matsbn** [comment]
Great that you created this branch @TomasTorsvik, that I believe will be useful for the GPU hackathon. I have not had time yet to test it myself. I would not include the large netCDF files in the branch. I guess users just have to copy them or we can place them in a common folder on the machine(s) to be used. I am fine with a corresponding feature branch in the BLOM repository.

**Comment by AleksiNummelin** [comment]
Thanks for putting this together @TomasTorsvik. It should be fine to leave out the netcdf files, because there is a python script in the regions_and_indices folder that will create these files for you anyway (and one needs to use that if the grid dimensions are changed).

**Comment by TomasTorsvik** [comment]
Thanks for the feedback. I will push the feature branch to the main repo now.
