### ISSUE TITLE
Build HAMOCC with Meson

### ISSUE THREAD

**Issue by nordmoen** [NorESMhub/BLOM#65]
Currently, adding all the source files in `hamocc` does not lead to a valid build with Meson (checkout the [`meson`](https://github.com/NorESMhub/BLOM/tree/meson) branch).

There are quite a few errors when compiling so I'm unsure how to proceed with enabling `hamocc`. Could someone with more experience comment on which files are required by `hamocc` and if there are special flags that are needed to compile. In addition, should `hamocc` be placed behind a feature flag in Meson in the same vein as `MPI` support?

With the new [`Actions` support](https://github.com/features/actions) added to the `meson` branch, any pull requests made are automatically tested. This can be seen under the `Actions` tab in the Github interface. So if you want to experiment, simply create a pull request against the `meson` branch and add `hamocc` support.

**Comment by JorgSchwinger** [comment]
To activate HAMOCC the preprocessor-flags
-DHAMOCC -DRESTART_BGC -DWLIN
are needed. This is the basic configuration. There are more flags to activate certain features.

**Comment by nordmoen** [comment]
It still does not compile. Could there be any compiler options that are needed? 

One of the first error that I encounter when compiling is the following
```bash
FAILED: blom.p/hamocc_restart_hamoccwt.F.o                                                                             
gfortran -Iblom.p -I. -I.. -Iphy -I../phy -I/usr/include -I/usr/lib64/gfortran/modules -fdiagnostics-color=always -pipe
 -D_FILE_OFFSET_BITS=64 -Wall -Wextra -g -fdefault-real-8 -fconvert=big-endian -DLEVITUS2X -DTKE -DTKEADV -DIDLAGE -DHA
MOCC -DRESTART_BGC -DWLIN -fopenmp -Jblom.p -o blom.p/hamocc_restart_hamoccwt.F.o -c ../hamocc/restart_hamoccwt.F      
../hamocc/restart_hamoccwt.F:34:72:                                                                                    
                                                                                                                       
   34 |      .             ,date%year,date%month,date%day,nstep,omask,rstfnm_ocn)                                      
      |                                                                        1                                       
Warning: Line truncated at (1) [-Wline-truncation]                                                                     
../hamocc/restart_hamoccwt.F:34:72:                                                                                    
                                                                                                                       
   34 |      .             ,date%year,date%month,date%day,nstep,omask,rstfnm_ocn)                                      
      |                                                                        1                                       
Error: Syntax error in argument list at (1)                                                                            
```

**Comment by nordmoen** [comment]
Solved using `-ffixed-line-length-none` with `gfortran`.
