### ISSUE TITLE
BLOM/iHAMOCC documentation

### ISSUE THREAD

**Issue by TomasTorsvik** [NorESMhub/BLOM#8]
@matsbn @JorgSchwinger @annefou @mvhulten 
Hi!
I just looked at the NorESM2 documentation page
https://noresm-docs.readthedocs.io/en/noresm2/
and I realized that there is not much documentation related to BLOM/iHAMOCC. With the new NorESM2 structure, the components should contain their own documentation, and there is already a "doc" folder with content provided by Marco.

Should we set up a readthedocs page for BLOM to host the documentation for BLOM/iHAMOCC? I'm assuming we want to use 'readthedocs', but perhaps this should also be a point for discussion? If you agree, I can go ahead and create a page based on the existing "doc" content.

**Comment by TomasTorsvik** [comment]
I wonder what the procedure should be for assigning people to an issue. I think it would be useful to get help from Marco here, so I went ahead and assigned him along with myself, but perhaps it should be up to each member to assign themselves?  I'm not even sure if there is a practical reason for assigning issues to people, other than to indicate that someone <has worked/is working/intends to work> on an issue.

**Comment by mvhulten** [comment]
I'm not sure what is best to do, but
+ it looks like [NorESM documentation](https://noresm-docs.readthedocs.io/en/noresm2/configurations/configurations.html) provides for user guides for the different components;
+ it may be useful if the [coding guidelines](https://github.com/NorESMhub/BLOM/blob/master/doc/coding-guidelines.rst), or some derived version, will become part of the [contribution](https://noresm-docs.readthedocs.io/en/noresm2/contribute/contribute.html) chapter; however, I remember at least one other component has its own coding guidelines, so then it may be better to either leave it in the BLOM repository or integrate it into the configurations section.

**Comment by TomasTorsvik** [comment]
Perhaps it makes sense to separate user guide from documentation for developers. As you say, it seems that the NorESM documentation will provide the user guide. We could also make use of the [wiki](https://github.com/NorESMhub/BLOM/wiki) to document things that are not needed for external users? At least, it doesn't make sense to split information over two readthedocs documents.

**Comment by matsbn** [comment]
Unfortunately, I have not had time to look much at the documentation. I think it make sense to place documentation that requires the full NorESM under NorESM, so e.g. BLOM relevant information for specifying compsets and configuration in coupled mode. Under BLOM documentation I would place information about how to contribute with code to BLOM (coding guidelines, git workflow etc.), information about configuring/building and running BLOM in standalone mode and other BLOM specific information. Maybe some of the documentation under NorESM can link to BLOM documentation? Probably an advantage to keep the documentation format consistent with NorESM.

**Comment by JorgSchwinger** [comment]
I agree with Mats. (Is there still the possibility to run BLOM/iHAMOCC stand alone? I thought the internal sea ice code was removed?). In any case, we should prioritize having a documentation (User Guide) for BLOM/iHAMOCC in the NorESM2 context, that is what people will be using. If resources allow we can think about adding more specific things for developers later. Coding guidelines should stay in the BLOM repository (does not make sense in the NorESM repository).

**Comment by TomasTorsvik** [comment]
The NorESM documentation use ReStructuredText (.rst) markdown that can be compiled with Sphinx to produce the ReadTheDocs output. The compilation procedure is defined by the NorESM/doc/Makefile, which defines the source dir as "." . Apparently, ReadTheDocs creates a clone of the NorESM repository before [building the documentation](https://docs.readthedocs.io/en/stable/builds.html). With this procedure, I think it is difficult to link NorESM documentation to .rst files in the BLOM repository. We can always include hyperlinks to external documents, but then the ReadTheDocs documentation will not be self contained. 

I agree that NorESM2 documentation should be a priority. This documentation should then be included in the NorESM repository, not the BLOM repository.

**Comment by TomasTorsvik** [comment]
I'm starting a wiki for git & gitHub things. This doesn't need to be in the general documentation.
