### ISSUE TITLE
Incorrect OpenMP directives in iHAMOCC

### ISSUE THREAD

**Issue by matsbn** [NorESMhub/BLOM#85]
The OpenMP directives in iHAMOCC need to be updated to be able to run NorESM with hybrid MPI/OpenMPI parallelisation in compsets with iHAMOCC enabled.

**Comment by TomasTorsvik** [comment]
@matsbn @IngoBethke 
I will have a look at this issue. Do you have a configured case with a hybrid MPI/OpenMP parallelisation that I can start testing from? I have not been running BLOM/iHAMOCC in hybrid parallelisation mode before, so any info you have will be much appreciated.

**Comment by TomasTorsvik** [comment]
BLOM/iHAMOCC compiles with gfortran without openMP, MPI and parallel netCDF, with CFCs and natural tracers enabled. Compilation fails with carbon isotopes (ciso), due to loading of variables from moduel (see #90).
