### ISSUE TITLE
Combine CPP flags with module "use <module>, only:"

### ISSUE THREAD

**Issue by TomasTorsvik** [NorESMhub/BLOM#90]
@JorgSchwinger @matsbn 

I found a bug when compiling with the CPP flag "cisonew" true. In beleg_param.F90 the variables iatmc13 and iatmc14 are not defined, because they are not loaded from the mo_param1_bgc module. This module is loaded with 
use mo_param1_bgc,  only: iatmco2,iatmnco2,iatmo2,iatmn2

The problem is that iatmc13 and iatmc14 are only defined when the "cisonew" flag is true, so it is not trivial to add these variables to the list that is loaded from the module. 
- Solution 1: remove "only" condition when using the module
- Solution 2: have different variants of the module load  directive, depending on CPP flags
- Solution 3: Remove the CPP flag settings, find some other method to turn these effect on and of

For now I suggest we use solution 1 in these cases, but maybe we should think about solution 3 for the long term?

**Comment by JorgSchwinger** [comment]
I agree this is a bug, good that you spotted this. 

The solution is easier: Just add iatmc13 and iatmc14 to the only list in beleg_parm.F90. If you check mo_param1_bgc you see that the indices are defined in any case. If the CPP flag "cisonew" is not set, then the indices are set to -1 but they will never be used (if they would be used this would be a bug). The same is currently done for iatmnco2 (which is set to -1 if CPP flag natDIC is not defined).
