### ISSUE TITLE
Document stand alone BLOM/iHAMOCC in wiki?

### ISSUE THREAD

**Issue by TomasTorsvik** [NorESMhub/BLOM#97]
@matsbn @nordmoen @AleksiNummelin @JorgSchwinger @milicak 
I suggest that we can use the wiki to document building and running stand alone BLOM/iHAMOCC. This is now in the README.md file, but that file is not really suitable for a long documentation text. The wiki is a better option for this because it can be structured over several pages for different sub-topics. At the moment I have just copied over the meson info from the README.md file. I was also thinking to include some description about the different test cases. What do you think, is this a way to go or do you prefer the current format with info in the README.md file?

**Comment by nordmoen** [comment]
I think moving the more detailed information to the wiki is a very good suggestion. I would keep some simple build instructions in the README so that new users immediately see where to start and then link to the wiki from the README for additional and more thorough information.
