### ISSUE TITLE
Extend the fuk95 with option to run iHAMOCC?

### ISSUE THREAD

**Issue by TomasTorsvik** [NorESMhub/BLOM#99]
@matsbn @JorgSchwinger 
It would be nice to have a stand-alone test case that can run iHAMOCC, so I was wondering if it would be possible to extend the fuk95 case to allow for this. There are some tracers that are initialized with GLODAP and WOA data in beleg_vars.F90. Are there any other obstacles that need to be handled?
I was thinking to just extend the existing mod_fuk95 with an additional subroutine, e.g. inihamocc_fuk95, to set the necessary variables. What do you think about this?

**Comment by JorgSchwinger** [comment]
It is difficult for me to judge how useful this will be in the end. I think such test cases are useful if you can see that the model does what you expect or how large the deviation from an ideal behaviour are. But I have no idea what results I would expect from the HAMOCC model in this setting (this is this idealized "one-eddy-case"?). Is there short wave radiation in this test-case? For the initialisation with WOA on would need lat/lon coordinates. Or one could initialise differently.

**Comment by TomasTorsvik** [comment]
@JorgSchwinger 
Yes, fuk95 is the "one-eddy-case". The main purpose I have in mind is the ability to test the interface between BLOM and iHAMOCC for a single threaded application. This is much easier to debug using standard debugging tools (e.g. gdb) than multi-threaded applications, and would make it easier to track variables that are moved between the model components. Also, if there are deviations between a single-threaded and multi-threaded version of the same case, you can be reasonably sure that there is an error in the parallelization procedure, so it would help to narrow down the search.
For the fuk95 case the iHAMOCC tracers will be artificial. I'm thinking that they can be initialized with a similar gradient as temperature (salinity is constant for this test case), but scaled to some sensible levels. There is no external forcing for the case, so no short wave radiation (?). If needed, could we set SWA to a constant or a simple sinusoidal signal?

**Comment by matsbn** [comment]
I think it would be useful to be able to include iHAMOCC in the fuk95 case just for technical testing. I also think the single column case could be very useful for iHAMOCC, as it should be able to simulate a specific ocean column with realistic vertical resolution at a specified geographic location.

**Comment by TomasTorsvik** [comment]
@matsbn Is there a working setup for the single column case now? I see that this fails during meson test runs.
